from typing import Callable, Union
from langchain_core.tools import BaseTool
from become_human.types.agent_manager import CallAgentKwargs
from become_human.tool import AgentTool

class Plugin:
    tools: list[Union[Callable, BaseTool, AgentTool]]
    commands: list[str] # TODO

    async def on_manager_init(self) -> None: ...
    async def on_manager_close(self) -> None: ...
    async def on_agent_init(self, agent_id: str, /) -> None: ...
    async def on_agent_close(self, agent_id: str, /) -> None: ...
    async def before_call_agent(self, call_agent_kwargs: CallAgentKwargs, /) -> None: ...
    async def after_call_agent(self, call_agent_kwargs: CallAgentKwargs, interrupted: bool, rejected_or_queuing: bool, /) -> None: ...
