from become_human.tool import AnyTool

class Plugin:
    tools: list[AnyTool] = []
    commands: list[str] = [] # TODO

    async def on_manager_init(self): ...
    async def on_manager_close(self): ...
    # 以下暂时没实现
    async def on_agent_init(self, agent_id: str): ...
    async def on_agent_close(self, agent_id: str): ...
    async def before_call_agent(self, agent_id: str): ...
    async def after_call_agent(self, agent_id: str): ...
